export const GAME_ACTIONS = {
  CREATE_GAME: 'CREATE_GAME',
  GET_GAME: 'GET_GAME',
  ADD_STORY: 'ADD_STORY',
  EDIT_STORY: 'EDIT_STORY',
  REMOVE_STORY: 'REMOVE_STORY',
  VOTE_STORY: 'VOTE_STORY'
};
